language: android
sudo: false
env:
  matrix:
    - ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a

android:
  components:
    - platform-tools
    - tools

    # Build Tools
    - build-tools-23.0.2

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

    # Emulator
    - sys-img-armeabi-v7a-android-23

cache:
  directories:
    - $HOME/.gradle/caches/2.8
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

before_install:
  - chmod +x gradlew
  - pip install --user codecov

before_script:
  #- echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew connectedAndroidTest -PdisablePreDex --continue --stacktrace
  - rm /home/travis/.gradle/caches/2.8/plugin-resolution/cache.properties.lock

after_success:
  - ./gradlew jacocoFullReport
  - codecov
