language: android
sudo: false
android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services
    - sys-img-armeabi-v7a-android-19

before_script:
    - chmod +x gradlew
    - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell settings put global window_animation_scale 0 &
    - adb shell settings put global transition_animation_scale 0 &
    - adb shell settings put global animator_duration_scale 0 &
    - adb shell input keyevent 82 &

env:
  global:
    - ADB_INSTALL_TIMEOUT=8

#Build, and run tests
script:
    - "./gradlew check -Dreceipt"
    - "./gradlew connectedCheck -Dreceipt"
