# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Lunch Pals
tagline:          'Have lunch with your pals!'
description:      'An android app that makes planning lunch with your friends easy and fun.'
url:              http://lunchpals.reustonium.com
baseurl:          /

author:
  name:           'Andy Ruestow'
  url:            https://twitter.com/reustonium

paginate:         5

# Custom vars
version:          0.3.1

github:
  repo:           https://github.com/reustonium/Lunch-Pals